// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package settings

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Boost() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ mode: 'manual', gain: 0 }\"><!-- Mode selection --><div><h3 class=\"text-lg font-semibold mb-3\">Mode</h3><div class=\"flex flex-col gap-2\"><label class=\"flex items-center gap-2\"><input type=\"radio\" value=\"manual\" x-model=\"mode\" class=\"radio radio-sm\"> <span>Boost (manual gain)</span></label> <label class=\"flex items-center gap-2\"><input type=\"radio\" value=\"normalize\" x-model=\"mode\" class=\"radio radio-sm\"> <span>Normalize (auto level)</span></label></div></div><!-- Gain slider --><div x-show=\"mode === 'manual'\" class=\"space-y-2 w-full\"><label class=\"font-medium\">Gain (dB)</label> <input type=\"range\" name=\"gain\" min=\"-20\" max=\"20\" x-model=\"gain\" class=\"range range-primary w-full\"><div class=\"flex justify-between text-base font-medium px-1\"><span>-20 dB</span> <span x-text=\"gain + ' dB'\"></span> <span>+20 dB</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
