// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package settings

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Metadata() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Title --><div><label class=\"font-medium\">Title</label> <input type=\"text\" name=\"title\" placeholder=\"Song Title\" class=\"input input-bordered w-full placeholder:text-gray-400 placeholder:opacity-60\"></div><!-- Artist --><div><label class=\"font-medium\">Artist</label> <input type=\"text\" name=\"artist\" placeholder=\"Artist Name\" class=\"input input-bordered w-full placeholder:text-gray-400 placeholder:opacity-60\"></div><!-- Album --><div><label class=\"font-medium\">Album</label> <input type=\"text\" name=\"album\" placeholder=\"Album Name\" class=\"input input-bordered w-full placeholder:text-gray-400 placeholder:opacity-60\"></div><!-- Year --><div><label class=\"font-medium\">Year</label> <input type=\"number\" name=\"year\" min=\"1900\" max=\"2100\" step=\"1\" placeholder=\"2025\" class=\"input input-bordered w-full placeholder:text-gray-400 placeholder:opacity-60\" onkeydown=\"return event.key >= '0' && event.key <= '9' || event.key === 'Backspace' || event.key === 'Delete' || event.key === 'ArrowLeft' || event.key === 'ArrowRight'\"></div><!-- Cover Art --><div><label class=\"font-medium\">Cover Art</label> <input type=\"file\" name=\"cover\" accept=\"image/*\" class=\"file-input file-input-bordered w-full\"><p class=\"text-xs opacity-70 mt-1\">Optional. JPG or PNG recommended.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
