// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package body

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Puchungualotsqui/sonic-tools/components/upload_area"
)

func Merge() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"pt-8 pb-12 px-6 max-w-3xl mx-auto\"><h2 class=\"text-3xl font-bold text-center mb-8\">➕ Merge Your Audio</h2><!-- Upload area (multiple files) -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = upload_area.UploadArea().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- File list preview --><div id=\"fileList\" class=\"mb-8 hidden\"><h3 class=\"text-lg font-semibold mb-3\">Selected Files</h3><ul class=\"list-disc pl-6 space-y-1 text-sm\"></ul><p class=\"text-xs opacity-70 mt-2\">Files will be merged in this order</p></div><!-- Options --><form hx-post=\"/tools/merge\" hx-target=\"#tool-content\" class=\"space-y-6\"><!-- Output format --><div><h3 class=\"text-lg font-semibold mb-3\">Output Format</h3><select name=\"format\" class=\"select select-bordered w-full\"><option value=\"mp3\" selected>MP3</option> <option value=\"wav\">WAV</option> <option value=\"flac\">FLAC</option> <option value=\"ogg\">OGG</option> <option value=\"aac\">AAC</option> <option value=\"m4a\">M4A</option></select></div><!-- Submit --><div class=\"pt-4 text-center\"><button type=\"submit\" class=\"btn btn-primary btn-lg\">Merge</button></div></form></section><script>\n\t  const fileInput = document.getElementById('mergeFiles');\n\t  const fileListDiv = document.getElementById('fileList');\n\t  const fileListUl = fileListDiv.querySelector('ul');\n\n\t  fileInput.addEventListener('change', () => {\n\t    fileListUl.innerHTML = ''; // clear old list\n\t    Array.from(fileInput.files).forEach((file, idx) => {\n\t      const li = document.createElement('li');\n\t      li.textContent = `${idx + 1}. ${file.name}`;\n\t      fileListUl.appendChild(li);\n\t    });\n\t    fileListDiv.classList.remove('hidden');\n\t  });\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
